pipeline:
  name: test
  identifier: test
  projectIdentifier: SELab
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gitglobalcon
        repoName: harness-python-demo
        build: <+input>
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: SELabCluster
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.harnessImage
                    image: python
                    shell: Sh
                    command: echo "Hello"
        delegateSelectors:
          - helm-delegate
